apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jam-app
  namespace: jam
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "off"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: jam.127.0.0.1.nip.io
      http:
        paths:
          - path: /users
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /jams
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /songs
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /uploads
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /events
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /spotify
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /health
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /docs
            pathType: Prefix
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /openapi.json
            pathType: Exact
            backend:
              service:
                name: jam-backend
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: jam-frontend
                port:
                  number: 80
