apiVersion: batch/v1
kind: Job
metadata:
  name: jam-backend-migrate
  namespace: jam
spec:
  backoffLimit: 4
  template:
    metadata:
      labels:
        app: jam-backend-migrate
    spec:
      restartPolicy: OnFailure
      containers:
        - name: migrate
          image: docker.io/ktistos/myjam-backend:dev-204a4ab-20260419191921
          imagePullPolicy: IfNotPresent
          command:
            - alembic
            - upgrade
            - head
          envFrom:
            - configMapRef:
                name: jam-backend-config
            - secretRef:
                name: jam-backend-secrets
