apiVersion: v1
kind: Service
metadata:
  name: jam-frontend
  namespace: jam
spec:
  selector:
    app: jam-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jam-frontend
  namespace: jam
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jam-frontend
  template:
    metadata:
      labels:
        app: jam-frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/ktistos/myjam-frontend:dev-204a4ab-20260419191921
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
              name: http
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 20
            periodSeconds: 10
