apiVersion: v1
kind: Secret
metadata:
  name: jam-secrets
  labels:
    app.kubernetes.io/name: jam
    app.kubernetes.io/part-of: jam
type: Opaque
stringData:
  POSTGRES_PASSWORD: password
  DATABASE_URL: postgresql://postgres:password@postgres:5432/jam
  MINIO_ACCESS_KEY: minioadmin
  MINIO_SECRET_KEY: minioadmin123
  SPOTIFY_CLIENT_ID: ""
  SPOTIFY_CLIENT_SECRET: ""
