apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: jam

resources:
  - namespace.yaml
  - app-config.yaml
  - app-secret.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - minio-init-job.yaml
  - backend-migrate-job.yaml
  - backend.yaml
  - frontend.yaml
  - ingress.yaml

images:
  - name: docker.io/ktistos/myjam-backend
    newTag: dev-204a4ab-20260419191921
  - name: docker.io/ktistos/myjam-frontend
    newTag: dev-204a4ab-20260419191921
